{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "supporthub.fullname" . }}
  labels:
    {{- include "supporthub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "supporthub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "supporthub.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "supporthub.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
  strategy:
    canary:
      steps:
        {{- toYaml .Values.rollout.canary.steps | nindent 8 }}
{{- end }}
